version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: itsmetrevor/palworld-dedicated-server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - TIMEZONE=America/New_York
      - COMMUNITY_SERVER=false
      - MULTITHREAD_ENABLED=true
      - BACKUP_INTERVAL=12 # hours, set to 0 to disable
      - BACKUPS_TO_KEEP=10 # oldest deleted first, set to 0 for unlimited
    volumes:
      - ./palworld:/palworld
    command: ./docker-script.sh